Sell_Buy/Controllers/CreateMagazineController.cs
using Sell_Buy.DB_Operation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sell_Buy.Controllers
{
    public class CreateMagazineController : Controller
    {
        // GET: CreateMagazine
        public ActionResult Index()
        {

            Sell_Buy_Entities db = new Sell_Buy_Entities();
            DB_Category cat = new DB_Category();
            var categories = cat.GetallCategory();


      

            ViewBag.Categories = categories;

            return View();
        }

        public ActionResult CreateMagazine(string nameMagazine , string photo , int idCategory)
        {
            Sell_Buy_Entities db = new Sell_Buy_Entities();
            Magazine mg = new Magazine
            {
                name_magazine = nameMagazine,
                C_image = photo,
                id_category = idCategory
            };
            int idmagazine = 0;
            DB_Magazine newMag = new DB_Magazine();
           idmagazine = newMag.InsertMagazine(mg);
           if (idmagazine != 0 || idmagazine != null)
            {
                int Id_user = 0;
                string logUser = Request.Cookies["Authentication"].Values.ToString();
               if(logUser != null)
               {
                   var idUser = (from u in db.Users
                                 where u.C_login == logUser
                                    select u.id).ToList();

                   if(idUser != null)
                   {
                       Id_user = Convert.ToInt32(idUser[0]);
                   }
               }
               
                UserMagazine usMag = new UserMagazine
                {
                    id_user = Id_user,
                    id_magazine = idmagazine
                };
                
                if(usMag != null)
                {
                    bool flagCreate = false;
                    DB_UsersMagazine usMagNew = new DB_UsersMagazine();
                   flagCreate= usMagNew.InsertUserMagazine(usMag);
                    if(flagCreate)
                    {
                        //ViewBag.CreateMagazineInfo = "Магазин создан";
                        return RedirectToAction("Index", "StartPage");
                    }
                }
            }

           return View();
            
        }
    }
}

Sell_Buy/Views/MasterPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/css/StyleSheet.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/css/AllStyle.css" type="text/css" />
    @RenderSection("scripts", false)

</head>
<body>
    @*<table style="width:100%;">
            <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>Logog of division site</tr>
            <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
            <tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
        </table>*@

    @using (Html.BeginForm())
    {
        <div>
            <div id="wrapper">
                <div id="banner">
                    <img class="imFon" src="~/Content/images/Logo.png" alt="~/  Content/images/Logo.png" height="200px" width="100%" />
                </div>

                <div id="navigation">
                    <ul id="nav" onclick="click()">

                        <li>@Html.ActionLink("About", "About", "MasterPage")</li>
                        <li style="float: right">
                           @* @if (Request.Cookies["lastVisit"] != null)
    {*@
                                @Html.ActionLink("Log out", "LogOut", "LogUser")
                            <li>@Html.ActionLink("WebShop", "index", "WebShop")</li>
                                <li>@Html.ActionLink("Basket", "index", "MyBasket")</li>
                                <li>@Html.ActionLink("Contact admin", "index", "ContactsToAdmin")</li>
                                <li>@Html.ActionLink("Update info", "Index", "UpdateInformation")</li>
                           @* }
    else
    {
        @Html.ActionLink("Log in", "index", "LogUser")
        <li style="float: right">@Html.ActionLink("Register", "index", "RegUser")</li>
    }
    </li>*@
        </ul>

    </div>
    <div id="content">
        @RenderBody()
        @*<asp:ContentPlaceHolder ID="ContentPlaceHolder1">

            </asp:ContentPlaceHolder>*@
                    </div>
                </div>

            </div>
    }

    <div>

    </div>
</body>
</html>

Sell_Buy/Views/_LayoutPage1.cshtml
@{
    string ErrorMessage = null;
     ErrorMessage=  ViewBag.ErrorMessage;
     List<string> countryList = ViewBag.Country;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/css/AllStyle.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    
    <link href="~/Content/css/btnStyle.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />

    <script src="~/Content/javascript/ModalForms.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="~/Content/javascript/AllScript.js"></script>
    <link href="~/Content/css/AuntificationStyle.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>
                <div class="collapse navbar-collapse">



                    @if (Request.Cookies["Authentication"] == null)
                    {
                        <ul class="nav navbar-nav col-lg-5">
                            <li class="active"><a href="#">Основная страница</a></li>
                            <li><a href="#about">О нас</a></li>
                            <li><a href="#contact">Контакти</a></li>
                        </ul>
                        <ul class=" LgTopStyle nav navbar-nav col-lg-5 ">

                            @*<a href="#contact">Вход/Регистрация</a>*@
                            <li>@Html.ActionLink("Вход/Регистрация", "Index", "Authentication")</li>

                        </ul>
                        <ul class="deviseStyleTop nav navbar-nav col-lg-5">
                            <li class="dropdown">
                                <a class=" dropdown-toggle" data-toggle="dropdown" href="#">Допонительно<span class="caret"></span></a>
                                <ul style="background:#101010;" class="dropdown-menu ">

                                    <li><a href="#contact">Вход/Регистрация</a></li>
                                </ul>
                            </li>

                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav col-lg-5">
                            <a id="go" class="navbar-brand" href="" onclick="getInfoUser()">Мой профиль</a>
                            <li><a href="#">Главная страница</a></li>
                            <li><a href="#contact">Контакти</a></li>
                        </ul>
                        <ul class=" LgTopStyle nav navbar-nav col-lg-5 ">
                            <li><a href="#contact">Корзина</a></li>
                            <li onclick="GetAllMagazineUser()"><a id="click" href="javascript:GetAllMagazineUser()" data-toggle="modal" data-target="#myModal">Мои магазины</a></li>
                            <li>@Html.ActionLink("Создать магазин", "Index", "CreateMagazine")</li>
                            <li>@Html.ActionLink("Выход", "LogOut", "Authentication")</li>
                        </ul>
                        <ul class="deviseStyleTop nav navbar-nav col-lg-5">
                            <li class="dropdown">
                                  
                                <a class=" dropdown-toggle" data-toggle="dropdown" href="#">Допонительно<span class="caret"></span></a>
                                <ul style="background:#101010;" class="dropdown-menu ">
                                    <li class="linkA"><a href="#contact">Корзина</a></li>
                                    <li><a href="#contact">Создать магазин</a></li>
                                    <li>@Html.ActionLink("Выход", "LogOut", "Authentication")</li>
                                </ul>
                            </li>

                        </ul>
                    }


                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">

            <div class="text-center">

            </div>

        </div><!-- /.container -->
        
        <div class="AllInfo">


        



            @if (ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <h3>@ErrorMessage</h3>
                </div>
            }
           
         @RenderBody()
         </div>

    </div>

<!-- Get user magazine-->
    <a href="#Allmagazine" id="manual-ajax">second example</a>

    <!-- The content of your page would go here. -->


    <div id="modal_form">
        <span id="modal_close">X</span>
        <div class="card">
            <img src="http://www.w3schools.com/howto/img_avatar.png" alt="Avatar" style="width:100%">
            <div class="container">


                <h3 class="dataInfo frName ">Фамилия  	<span class="infoFirstName label label-default" onclick="infoFirstNameUser(this)"></span></h3>
                <input class="updFirstName updateInfouser" autofocus="true" data-val="true" data-val-required="The Login field is required." id="username" name="firstName" placeholder="Фамилия" required="true" type="text" value="">
               

                <h3 class="dataInfo lsName">Имя 		<span class="infoLastName label label-default" onclick="infoLasttNameUser(this)">Василий</span></h3>
                <input class=" updLastName updateInfouser" autofocus="true" data-val="true" data-val-required="The Login field is required." id="username" name="lastName" placeholder="Имя" required="true" type="text" value="">

                <h3 class="dataInfo mdlName">Отчество 	<span class="infoMiddleName label label-default" onclick="infoMiddleNameUser(this)">Васильевич</span></h3>
                <input class="udMiddleName updateInfouser" autofocus="true" data-val="true" data-val-required="The Login field is required." id="username" name="middleName" placeholder="Отчество" required="true" type="text" value="">

                <h3 class="dataInfo usPhone">Номер 	<span class="infoPhone label label-default" onclick="infoPhoneUser(this)">0684247364</span></h3>
                <input class=" updPhone updateInfouser" autofocus="true" data-val="true" data-val-required="The Login field is required." id="username" name="phone" placeholder="Номер" required="true" type="text" value="">

                <h3 class="dataInfo usMail">Емейл 	<span class="infoMail label label-default" onclick="infoMailUser(this)">vadimmm972@gmail.com</span></h3>
                <input class="updMail updateInfouser" autofocus="true" data-val="true" data-val-required="The Login field is required." id="username" name="mail" placeholder="Емейл" required="true" type="text" value="">

                <h3 class="dataInfo usCountry">Страна 	<span class="infoCountry label label-default" onclick="infoCountryUser(this)">Украина</span></h3>
                @*<input class="updCountry updateInfouser" autofocus="true" data-val="true" data-val-required="The Login field is required." id="username" name="country" placeholder="Страна" required="true" type="text" value="">*@
                <select id="pullCountry" class="updCountry updateInfouser"></select>
                
                <h3 class="dataInfo usRegion">Регион 	<span class="infoRegion label label-default" onclick="infoRegionUser(this)">Ровенская обл.</span></h3>
                @*<input class="updRegion updateInfouser" autofocus="true" data-val="true" data-val-required="The Login field is required." id="username" name="region" placeholder="Регион" required="true" type="text" value="">*@
                <select id="pullRegions" class="updRegion updateInfouser"></select>
                
                <h3 class="dataInfo usSity">Город 	<span class="infoSity label label-default" onclick="infoSityUser(this)">г.Ровно</span></h3>
               @* <input class="updSity updateInfouser" autofocus="true" data-val="true" data-val-required="The Login field is required." id="username" name="sity" placeholder="Город" required="true" type="text" value="">*@
                <select id="pullSites" class="updSity updateInfouser"></select>
                
                 @* <a href="#" class="updateInfo col-xs-4 button24" onclick="functionInfoUpdate()">Изменить</a>*@
                <a  href="#" class="SaveUpdateInfo col-xs-4 button25">Сохранить</a>
            </div>
        </div>
    </div>

    
    <div id="overlay"></div>



    <!-- Modal get all magazines -->
    <div class="container">
       

      
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Список ваших магазинов</h4>
                    </div>
                    <div class="myMagazines modal-body">
                       
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


</body>
</html>
<script>
    $(".dropdown-menu>li>a").css('color', 'white');


    $(".updateInfo").on("click", function () {
        $(".label").css('display', 'none');
        $(".updateInfouser").css('display', 'block');
    });

    $(document).ready(function () {
        $('a#go').click(function (event) {
            event.preventDefault();
            $('#overlay').fadeIn(400,
                function () {
                    $('#modal_form')
                        .css('display', 'block')
                        .animate({ opacity: 1, top: '20%' }, 300);
                });
        });

        $('#modal_close, #overlay').click(function () {
            $('#modal_form')
                .animate({ opacity: 0, top: '10%' }, 200,
                    function () {
                        $(this).css('display', 'none');
                        $('#overlay').fadeOut(400);
                    }
                );
        });
    });

    $(".SaveUpdateInfo").prop("disabled", true);


    $(".row").css('margin','0');
    </script>